---
- hosts: all
  remote_user: root
  vars_files:
    - ./var/ubuntu.yml
  tasks:
#  - name: change source.list
#    template: src=./template/source-list.temp dest=/etc/apt/sources.list
#    when: change_source | match("true")
  - name: Install apt packages
    apt:
      pkg: "{{ item }}"
      state: "present"
    with_items: "{{ packages }}"
  - name: configuration modules
    template: src=./template/modules.template dest=/etc/modules
    notify: 
    - restart ntp
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted

- hosts: infra1
  remote_user: root
  tasks:
  - name: conf interface
    template: src=./template/infra1.interface.temp dest=/etc/network/interfaces
    notify:
    - restart network
  handlers:
    - name: restart network
      shell: "/sbin/ifdown -a && /sbin/ifup -a && /sbin/ifconfig ens3 0"
- hosts: compute1
  remote_user: root
  tasks:
  - name: conf interface
    template: src=./template/compute1.interface.temp dest=/etc/network/interfaces
    notify:
    - restart network
  handlers:
    - name: restart network 
      shell: "/sbin/ifdown -a && /sbin/ifup -a && /sbin/ifconfig ens3 0"
- hosts: all
  remote_user: root
  tasks:
  - name: update apt
    shell: "/usr/bin/apt-get update"
